let rootURL = 'http://dmls.iust.ac.ir';
let baseURL = rootURL + ':8099';
let ontologyURL = rootURL + ':8090';
let mappingsURL = rootURL + ':8090';
let reportsURL = rootURL + ':8092';
let xxxURL = rootURL + ':8091';
let feedbackURL = rootURL + ':8101';
let runURL = rootURL + ':8089';
let virtuosoURL = rootURL + ':8890';